name = "s-danny-is"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
DOMAIN = "s.danny.is"
API_SECRET = "dev-secret-123"

[[kv_namespaces]]
binding = "URLS_KV"
preview_id = "preview-kv-id"
id = "production-kv-id"

[env.production]
[[env.production.kv_namespaces]]
binding = "URLS_KV"
id = "production-kv-id"