name = "dny-li"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
DOMAIN = "dny.li"
# Use wrangler secret put API_SECRET for production

[[kv_namespaces]]
binding = "URLS_KV"
preview_id = "3176486d69994df5a5cb97cce14bb704"
id = "eaef839073424c4db47c1a38d0598b28"

[env.production]
[[env.production.kv_namespaces]]
binding = "URLS_KV"
id = "eaef839073424c4db47c1a38d0598b28"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
